version: '3.8'
services:
  db:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - teamsync_network

  flyway:
    image: flyway/flyway:10
    command: -url=jdbc:postgresql://db:5432/postgres -schemas=public -user=postgres -password=123 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    networks:
      - teamsync_network

  backend:
    image: prithuanan/teamsync-backend:${TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      AZURE_CONNECTION_STRING: ${{ secrets.AZURE_CONNECTION_STRING }}
      AZURE_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
      AZURE_ACCOUNT_NAME: ${{ secrets.AZURE_ACCOUNT_NAME }}
      AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
    depends_on:
      db:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - teamsync_network

volumes:
  db_data: 

networks:
  teamsync_network:
    external:
      name: teamsync_network
