name: CI/CD → Azure VM

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM over SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:        ${{ secrets.VM_HOST }}
          username:    ${{ secrets.VM_USER }}
          key:         ${{ secrets.SSH_KEY }}
          port:        22
          strict:      false

          script: |
            set -eux
            mkdir -p ~/apps/teamsync-backend
            cd ~/apps/teamsync-backend

            if [ ! -d .git ]; then
              git clone git@github.com:prithu-anan/teamsync-backend.git .
            else
              git fetch origin master
              git reset --hard origin/master
            fi

            docker compose pull || true
            docker compose up -d --build
