name: Build & Deploy Backend

on:
  push:
    branches: [ "master" ]   # or "main" if that's your default

permissions:
  contents: read

jobs:
  deploy:
    name: Pull & Deploy on Azure VM
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     22
          script: |
            cd ~/teamsync/teamsync-backend

            # 1) Pull the latest commits from your repo
            git pull origin master

            # 2) Recreate only what's changed, in detached mode
            AZURE_CONNECTION_STRING=${{ secrets.AZURE_CONNECTION_STRING }} \
            AZURE_CONTAINER_NAME=${{ secrets.AZURE_CONTAINER_NAME }} \
            AZURE_ACCOUNT_NAME=${{ secrets.AZURE_ACCOUNT_NAME }} \
            AZURE_SAS_TOKEN=${{ secrets.AZURE_SAS_TOKEN }} \
            docker compose down -v && docker compose up -d --build
