name: Build & Deploy Backend

on:
  push:
    branches: [ "master" ]   # or "main" if that's your default

permissions:
  contents: read

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build & push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            prithuanan/teamsync-backend:latest
            prithuanan/teamsync-backend:${{ github.sha }}

  deploy:
    name: Pull & Run on Azure VM
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     22
          script: |
            cd ~/teamsync/teamsync-backend
            
            export TAG=${{ github.sha }}
            
            # Pull your prebuilt images
            docker compose pull
            
            # Tear down any old stack
            docker compose down -v
            
            # Recreate db, flyway and backend with the proper network & env
            docker compose up -d


