name: Sync Upstream → Fork

on:
  schedule:
    - cron: "0 0 * * *"     # every night at 00:00 UTC
  workflow_dispatch:       # manual trigger

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0      # full history

      - name: Configure Git
        run: |
          git config user.name  "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Configure 'ours' merge driver
        run: git config merge.ours.driver true

      - name: Fetch & merge from upstream
        run: |
          git remote add upstream https://github.com/suhashines/teamsync-backend.git
          git fetch upstream master
          git checkout master
          git merge upstream/master --no-ff --no-edit

      - name: Push merged changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
